-- Hand-written: Module 6 image variants pipeline (thumbnail only, v1).
-- Generated by sharp after clean ClamAV scan, stored alongside original
-- in the same bucket with key suffix `__thumb.webp`. /media/:id/stream
-- supports ?variant=thumbnail.
--
-- v1 ships a single 256x256 cover-cropped webp thumbnail for image
-- purposes (avatar/listing_cover/listing_gallery). KYC documents do
-- not get variants (private bucket, no FE consumer needs them).
-- v2 should switch to jsonb for multiple sizes + lossless source.

ALTER TABLE "media_objects" ADD COLUMN IF NOT EXISTS "thumbnail_key" text;
